apiVersion: "apiextensions.k8s.io/v1beta1"
kind: "CustomResourceDefinition"
metadata:
  name: "kloians.crd.kloia.com"
spec:
  group: "crd.kloia.com"
  version: "v1alpha1"
  scope: "Namespaced"
  names:
    plural: "kloians"
    singular: "kloian"
    kind: "Kloian"
  validation:
    openAPIV3Schema:
      required: ["spec"]
      properties:
        spec:
          required: ["name"]
          properties:
            replicas:
              type: "integer"
              minimum: 1
            name:
              type: "string"
            surname:
              type: "string"
            title:
              type: "string"